-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here

-- Note: Auto-formatting is now disabled globally in options.lua
-- The following autocmd is no longer needed but kept for reference
-- vim.api.nvim_create_autocmd({ "FileType" }, {
--   pattern = { "lua" , 'python', 'sh'},
--   callback = function()
--     vim.b.autoformat = false
--   end,
-- })
